### PR TITLE
Fix compatibility issue with node 12+

### PR DESCRIPTION
**Pull request by ywongau**
Fixed breakage from hapi  v9

node_modules\corsproxy\node_modules\hapi\lib\defaults.js:49
            uploads: Os.tmpDir(),
                        ^

TypeError: Os.tmpDir is not a function
    at Object.<anonymous> (C:\Users\e860738\source\webdataconnector\node_modules\corsproxy\node_modules\hapi\lib\defaults.js:49:25)

Force hapi's resolution to  v16

Most of the dependencies are 4 years behind, you might want to upgrade them all before it's too late

### CODE REVIEW

**Comment by theoutlander** [comment]
Thanks for the PR. There is a problem with that library when package-lock doesn't exist. I don't think we can merge this.

**Comment by theoutlander** [comment]
https://github.com/rogeriochaves/npm-force-resolutions/issues/10

**Comment by ywongau** [comment]
Should the lock file then be checked in? It's the official recommendation, so that the builds are consistent

**Comment by jason-costello** [comment]
This corrected an issue I could not fix using the current master branch.  I was getting corsproxy errors and couldn't get the server to start.   cloned Ywongau:master and rpm install -production && rpm start worked like a charm.

**Comment by chenteng2016** [comment]
@ywongau thanks a lot for opening the pull request and helping improve webdataconnector!

Your solution to force hapi version to let corsproxy work is pretty brilliant! Another way we also tried is to add Os.tmpDir = Os.tmpdir; into ./node_modules/hapi/lib/defaults.js after the line of requiring os package through a pre-start script.

After some discussions, based on that even the latest corsproxy is out-of-date for 5 years and it does not work well with later dependency versions, maybe it's time for us to deprecate corsproxy usage. Nick and I migrated it and tested the change with different node versions. Would you please pull the latest master and help check whether it works for your scenario? Thanks again!

**Comment by chenteng2016** [comment]
Please help re-open or let us know if there is still any issue related, thanks a lot for contributing to webdataconnector!

**Pull request closed without merging**
