### PR TITLE
Update community_connectors.json

### PR DESCRIPTION
**Pull request by NeelShah00**
I had prepared my WDC with the help of Javascript and html. It is divided into two parts:
1) I had made html website on the Blogger
2) I had hosted Javascript file on google Drive

Working: when the user clicks on the get data button it executes the file uploaded on google drive

Data: I had acquired precise data from the official government website of india for coronavirus

Website: https://www.covid19india.org

### CODE REVIEW

**Comment by NeelShah00** [comment]
What should I do to resolve this?

**Comment by illonage** [comment]
Hi @NeelShah00
Thank you for submitting your WDC.
Your WDC is working but the interface is confusing. Did you try to host it on a different platform? We listed some options here: https://tableau.github.io/webdataconnector/docs/wdc_hosting_and_submissions.html

Can you also update the description to give your details on the data, please?

**Comment by NeelShah00** [comment]
Absolutely, I had prepared my WDC with the help of Javascript and html. It is divided into two parts:
1) I had made html website on the Blogger
2) I had hosted Javascript file on google Drive

Working: when the user clicks on the get data button it executes the file uploaded on google drive

Data: I had acquired precise data from the official government website of india for coronavirus

Website: https://www.covid19india.org

**Comment by illonage** [comment]
Hi - Do you think you can edit the HTML. The Blogger interface might be confusing for users.

**Comment by NeelShah00** [comment]
Yes, lately I had made changes to the HTML and removed ambiguous components from them. Kindly, check the update and let me know if any changes are necessary.

**Pull request merged**
