### PR TITLE
Update the simulator to behave closer to a Web Data Connector

### PR DESCRIPTION
**Pull request by dbecks**
This change updates the simulator to open the WDC in a new pop up window.  This makes it possible to test OAuth scenarios.  The data fetching phase is then run in an iframe that gets regenerated on each fetch to better simulate the refresh of state in the real WDC.

### CODE REVIEW

**Comment by benlower** [comment]
@dbecks thanks for submitting this! we don't (yet) have a contribution policy in place. please hang tight while we spend some time on this. i'd like to be able to accept useful contributions like this :)

**Comment by benlower** [comment]
Closing this PR since this new simulator has evolved. We will merge this in later after it has had time to simmer a bit more.

**Comment by benlower** [comment]
Should not have closed.  Leaving open while the new simulator develops.

**Comment by lbrendanl** [comment]
We are taking this through an alternate pull request.

**Pull request closed without merging**
