### PR TITLE
Add my COVID-19 (CA) Emergency Service Provider Data!

### PR DESCRIPTION
**Pull request by lshpaner**

### CODE REVIEW

**Comment by lshpaner** [comment]
> [Coverage Status](https://coveralls.io/builds/32410581)
> 
> Coverage remained the same at 98.913% when pulling **[66dd6d5](https://github.com/tableau/webdataconnector/commit/66dd6d5605076e80dbccc8fca3c74b9abfc7fec2) on lshpaner:patch-1** into **[ef3f320](https://github.com/tableau/webdataconnector/commit/ef3f32044a55fbc502170416c4481f5f753dc97b) on tableau:master**.

Awesome. What does this mean? When will I see my connector on the Tableau Community Portal (https://tableau.github.io/webdataconnector/community/)?

**Comment by illonage** [comment]
Hi Leon - Thank you for submitting ur WDC. It looks good, but it seems you paste the source code URL in the wrong record. Can you update that, please? I will approve once you made you change

**Comment by lshpaner** [comment]
Hi Geraldine,

I went ahead and updated the source code URL to:
https://github.com/lshpaner/lshpaner/tree/master/content/datasets/covid_19_data/EmergencyServiceProvidersinCA

Best,
Leon Shpaner

email: lshpaner@ucla.edu
cell: (310) 721-7126

**Comment by lshpaner** [comment]
Hi Geraldine,

Thank you so much! I also went ahead and updated  the description on
COVID-19 Emergency Service Providers in CA (removing unnecessary capital
letters), and more importantly, I created a new data connector: "Geothermal
Wells in the State of CA today.

Thank you,

Leon Shpaner

email: lshpaner@ucla.edu
cell: (310) 721-7126

**Pull request merged**
