### PR TITLE
remove https from the heroku link for Census WDC

### PR DESCRIPTION
**Pull request by port80labs**

### CODE REVIEW

**Comment by lbrendanl** [comment]
Hey @port80labs, I was testing your connector and I am having trouble getting it to run inside Tableau. When I try to run it (both the http and https version), I get the following error when the page loads: "ReferenceError: Can't find variable: _wdc file: undefined line: 1".  Nothing appears to happen once I hit Get Data either.  Are you seeing the same thing?  

I know this was working previously for me when I checked it out a few weeks ago (awesome connector by the way!).

**Comment by port80labs** [comment]
you are right.. let me see whats up. /ht

**Comment by brandoconnor** [comment]
Any update on this, @port80labs ?

**Comment by lbrendanl** [comment]
@port80labs I am closing this since we never received an update and we have a new process for submitting connectors to the community gallery now.  http://tableau.github.io/webdataconnector/docs/wdc_hosting_and_submissions

**Pull request closed without merging**
