### PR TITLE
Update community_connectors.json

### PR DESCRIPTION
**Pull request by mdkarp**
Created a WDC for Quick Base, and would folks to use it!

### CODE REVIEW

**Comment by KeshiaRose** [comment]
Awesome Mike! One thing, is there a page that get's closer to the actual web data connector instead of the main page. We try to keep the links as the actual wdc link instead of the promotional page.

**Comment by mdkarp** [comment]
Thanks @KeshiaRose - does that mean that the user should be able to try the connector if they just put that URL directly into the WDC box?

**Comment by KeshiaRose** [comment]
That would be ideal, however, I see your web data connector is behind a paywall so not quite sure what would be best. Especially since that page doesn't load in Desktop.

**Comment by mdkarp** [comment]
Maybe if I offered a free trial, like a bunch of the others I looked at so it worked right off the bat? Would that meet the requirements?  @KeshiaRose

**Comment by KeshiaRose** [comment]
Doesn't necessarily need to be a free trial, just that the pay site doesn't work in the web data connector browser and isn't a great experience. Is there a link that someone who already has an account would use? Maybe the login page directly before the WDC?

**Pull request closed without merging**
