### PR TITLE
corsproxy migration

### PR DESCRIPTION
**Pull request by chenteng2016**
1) simulator corsproxy issue:
    - the issue is that corsproxy not able to run with node with version >= 13, and the reason is the existing corsproxy is outdated for 5 years and is rely on old version dependencies:
corsproxy

corsproxy-dependency

2) specific error:
   - the error in the case is that corsproxy is reply on hapi v9 which utilizes Os.tmpDir() which is not supported anymore for node >= v13.
tmpDir

3) candidate fixes:
    - there are folks who nicely suggested updating hapi version singly but because other dependencies of corsproxy are also pretty old, so based on some draft testings only some specific versions of hapi (a subset of v16, v17) will work; updating all corsproxy dependencies also brings problems because corsproxy itself is outdated for 5 years.
    - one ad-hoc solution without updating the dependency versions is to add line Os.tmpDir = Os.tmpdir; into ./node_modules/hapi/lib/defaults.js after the line of requiring os package through a pre-start script, it will work with the current dependencies but is pretty hacky.

4) proposed fix:
    - as Nick (theoutlander) suggested, we probably would like to migrate from utilizing the deprecated corsproxy to utilizing up-to-date cors proxy and keep the simulator project having the same functionalities. This PR is trying to utilize cors-anywhere and is working with various node versions by a quick verification.
update-corsproxy

5) actions needed and are ongoing for now:
    - more tests on more envs / node versions need to be done for validating the update.
    - security problems need to be fixed across the dependencies.
    - 5 mocha test cases are not able to be passed, although probably are not related to cors proxy but we would fix them to ensure quality.
    while doing above will update this PR accordingly.

### CODE REVIEW

**Comment by KeshiaRose** [comment]
Nice! I'm glad you found an alternative that seems to be as simple!

**Comment by chenteng2016** [comment]
> Nice! I'm glad you found an alternative that seems to be as simple!
Thanks, Keshia! Nick suggests this change. More testings are ongoing.

**Comment by theoutlander** [comment]
@chenteng2016 are you waiting on fixing travis before merging this change?

**Review by theoutlander — APPROVED** [review]

**Comment by theoutlander** [comment]
@chenteng2016 please merge once tests/travis-ci is passing

**Comment by chenteng2016** [comment]
Thanks for Nick's instructions and review.

**Pull request merged**
